### ISSUE TITLE
Simulation progress bar

### ISSUE THREAD

**Issue by jellebakker96** [NyanCAD/Mosaic#84]
Maybe also show simulations before they are finished?

**Comment by pepijndevos** [comment]
It already streams data from the simulator, so the only part where you don't see progress is while it's loading the schematic into the simulator.

**Comment by pepijndevos** [comment]
I think error reporting can be improved in cases where there is a problem with connecting to the simulator, but since you already get streaming data as soon as the simulation has started, and can watch the simulator output in the terminal window at the bottom, I don't see any value in a progress meter.

**Comment by jellebakker96** [comment]
Ah, ok

**Comment by jellebakker96** [comment]
> I think error reporting can be improved in cases where there is a problem with connecting to the simulator, but since you already get streaming data as soon as the simulation has started, and can watch the simulator output in the terminal window at the bottom, I don't see any value in a progress meter.

This was indeed the problem.
